### ISSUE TITLE
Action does not have a version output.

### ISSUE THREAD

**Issue by MisterTimn** [ltv/standard-version-action#52]
When trying out this action I noticed that there is no version variable outputted though the documentation shows an example of it:
```
- name: Bump version
  id: release
  uses: ltv/standard-version-action@v2
  with:
    releaseAs: 'minor'
- run: |
    echo "Released version: $VERSION"
  env:
    VERSION: ${{ steps.release.output.version }}
```

Having the version number as output, or even as separate parts (major, minor, patch numbers) can be extremely handy for more complex release workflows.
